### ISSUE TITLE
Create unit/replenish

### ISSUE THREAD

**Issue by karhodes** [reactivepixel/Gravity#31]
Develop the routes & logic associated with sku/replenish

Full documentation found in readme.

Steps:
1.  Available units of a sku is compared to trigger qty of sku.  If available units is less than trigger qty, replenishment qty is added to the current shipment in shipment_units

Tables & columns needed:
1.  sku (qty on hand / available, trigger qty, replenish qty)
2.  shipment (uuid, timestamp, status) --> Every 5 minutes a new shipment is added to the table.  Statuses could be "current" (adding units to shipment) and "shipped" (sent to /unit/create)
3.  shipment_units (shipment_id, sku, qty)

**Comment by reactivepixel** [comment]
Renamed from `sku/replenish` to `unit/replenish` to reflect the naming scheme of the other areas of the application.
