### ISSUE TITLE
Gulp file double executes the server.js file

### ISSUE THREAD

**Issue by reactivepixel** [reactivepixel/Gravity#35]
When statically adding a entry to the db We found out that 2 entries are added, tracked it down to the gulp file causing this. May present a problem in the future, none now.

-Cheers! :beers:

**Comment by bmbergh** [comment]
Okay, I will keep an eye on this and will make any changes when needed.

**Comment by icarlosmendez** [comment]
Corrected issue with `gulpfile.js` where `server.js` was double executed. The issue was that `nodemon` was running before the 'build' was completed. This issue is resolved. I will push today in class.
