### ISSUE TITLE
Create unit tests for pods

### ISSUE THREAD

**Issue by karhodes** [reactivepixel/Gravity#67]

**Comment by bmbergh** [comment]
this is a test

**Comment by bmbergh** [comment]
![giphy](http://media4.giphy.com/media/l0Nwvo3slpo6nS0PC/200.gif)

**Comment by bmbergh** [comment]
![tifgif](http://media3.giphy.com/media/Zh22010CGdjbi/200.gif)

**Comment by bmbergh** [comment]
![tifgif](http://media4.giphy.com/media/l0Nwvo3slpo6nS0PC/200.gif)

**Comment by bmbergh** [comment]
![tifgif](http://media1.giphy.com/media/l2JIeRIge5SQcpaP6/200.gif)

**Comment by bmbergh** [comment]
![tifgif](http://media1.giphy.com/media/l2JIeRIge5SQcpaP6/200.gif)
