### ISSUE TITLE
Readme Update

### ISSUE THREAD

**Issue by karhodes** [reactivepixel/Gravity#95]
Hi Carlos,

Please make the following changes to the readme so that it aligns with the db:

1.  order/create:  add qty to units in the request & response
2.  order/find:  add qty to units in the response
3.  order/update/ship:  should we add the shipping method?
4.  order/picking:  change method to GET.  See /packaging as example.  Include roll-up qty
5.  package/create:  note that packages is a reserved word; we need to use packs.  the request is an order_id.  the response is the pkg_id, order_id, pkg_units (sku & qty).  No need for recipient or shipping.
6.  package/find:  change method to GET.  Should return pkg_id, order_id, status, pkg_units (sku & qty)
7.  unit/replenish:  rename to unit/update/replenish (to match the other /update routes)
8.  unit/recieving:  change method to GET.  Only return roll-up of units and array of only unit_ids
9.  unit/available, picking, packaging, inspecting, shipping, shipped:  same as unit/recieving
10.  delete all sku endpoints
11.  rename shipments to replenishments.  (but we could in theory just delete all shipment endpoints b/c they're not developed enough
12.  worker/find:  change method to GET.  should return worker_id, name, job_id (picker, packer, shipper...), status, updatedAt, order_id.  Possibly delete assigned field since it doesn't line up in the db
13.  worker/available:  change method to GET,  add roll-up
14.  let's discuss worker/occupied in real life.  I need to understand how you envision it used.
15.  worker/inspecting, /picking, /packaging...: change method to GET.  add roll-up
16.  pods/find:  changed method to GET.  Include status, updatedAt and last_maintain in response.  We also need to discuss payload in real life.
17.  pod/available:  need to discuss, not sure if this is needed
18.  pod/loading, /picking:  changed method to GET.  add roll-up numbers and only return pod_id.

**Comment by icarlosmendez** [comment]
The majority of the recommendations here were completed by Carlos Mendez. I am closing this issue now that our class related involvement has expired.
